### ISSUE TITLE
Preview Posts is not showing preview content when preview mode is enabled.

### ISSUE THREAD

**Issue by jacob-alxndr** [datocms/datocms-astro-blog-demo#1]
**Problem:** 
When previewing draft content on the post pages we are not fetching from the preview graphQL api, therefor not seeing draft content out of the box.

**Recommended solve:** 
Append "preview" to Preview/ Posts /[slug].astro response fetch request url string

**Out of the box:**
` const response = await fetch(
  'https://graphql.datocms.com/',
  {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': `Bearer ${import.meta.env.ASTRO_EXAMPLE_CMS_DATOCMS_API_TOKEN}`,
    },
    body: JSON.stringify(
      graphqlRequest
    ),
  })
`

**Solution:**
`  const response = await fetch(
  **'https://graphql.datocms.com/preview',**
  {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Accept': 'application/json',
      'Authorization': `Bearer ${import.meta.env.ASTRO_EXAMPLE_CMS_DATOCMS_API_TOKEN}`,
    },
    body: JSON.stringify(
      graphqlRequest
    ),
  })`

**Comment by marcelofinamorvieira** [comment]
Hey @jacob-alxndr we appended that to the preview endpoint! Thank you for letting us know :)
